// Traducción de las descripciones de efecto de los movimientos (EN -> ES, España).
// WHOLE = traducción exacta de las 350 descripciones del formato (calidad).
// Si llega una no listada (movimiento nuevo), se usa el traductor por reglas.

const WHOLE = {
  " + 20 power for each of the user's stat boosts.": "+20 de potencia por cada mejora de stat del usuario.",
  "+1 SpD, user's next Electric move 2x power.": "+1 Def. Esp.; el próximo movimiento Eléctrico del usuario tiene doble potencia.",
  "+50 BP/hit on user. Max 6 hits. Resets on switch-out.": "+50 de potencia por golpe acumulado. Máx. 6. Se reinicia al cambiar.",
  "+50 power for each time a party member fainted.": "+50 de potencia por cada aliado debilitado.",
  "-1 evasion; ends user and target hazards/terrain.": "-1 Evasión; elimina trampas y campo de ambos lados.",
  "1.5x damage if foe holds an item. Removes item.": "1,5x de daño si el rival lleva objeto. Se lo quita.",
  "1/8 of target's HP is restored to user every turn.": "Cada turno, el usuario recupera 1/8 de los PS del objetivo.",
  "10% chance to burn the foe(s).": "10% de prob. de quemar a los rivales.",
  "10% chance to burn the target.": "10% de prob. de quemar al objetivo.",
  "10% chance to burn. 10% chance to flinch.": "10% de prob. de quemar. 10% de hacer retroceder.",
  "10% chance to freeze foe(s). Can't miss in Snow.": "10% de prob. de congelar a los rivales. No falla con nieve.",
  "10% chance to freeze the target.": "10% de prob. de congelar al objetivo.",
  "10% chance to freeze. 10% chance to flinch.": "10% de prob. de congelar. 10% de hacer retroceder.",
  "10% chance to lower the target's Attack by 1.": "10% de prob. de bajar el Ataque del objetivo en 1.",
  "10% chance to lower the target's Sp. Atk by 1.": "10% de prob. de bajar el At. Esp. del objetivo en 1.",
  "10% chance to lower the target's Sp. Def by 1.": "10% de prob. de bajar la Def. Esp. del objetivo en 1.",
  "10% chance to make the target flinch.": "10% de prob. de hacer retroceder al objetivo.",
  "10% chance to paralyze the target.": "10% de prob. de paralizar al objetivo.",
  "10% chance to paralyze. 10% chance to flinch.": "10% de prob. de paralizar. 10% de hacer retroceder.",
  "10% chance to poison adjacent Pokemon.": "10% de prob. de envenenar a los Pokémon adyacentes.",
  "10% chance to raise all stats by 1 (not acc/eva).": "10% de prob. de subir todas las stats en 1 (no prec/eva).",
  "10% chance to raise the user's Defense by 1.": "10% de prob. de subir la Defensa del usuario en 1.",
  "100% burns a target that had a stat rise this turn.": "Quema seguro al objetivo que haya subido una stat este turno.",
  "100% chance lower adjacent Pkmn Speed by 1.": "100% de bajar la Velocidad de los Pokémon adyacentes en 1.",
  "100% chance to burn the target.": "100% de prob. de quemar al objetivo.",
  "100% chance to confuse the target.": "100% de prob. de confundir al objetivo.",
  "100% chance to lower target's Sp. Atk by 1.": "100% de bajar el At. Esp. del objetivo en 1.",
  "100% chance to lower the foe(s) Attack by 1.": "100% de bajar el Ataque de los rivales en 1.",
  "100% chance to lower the foe(s) Sp. Atk by 1.": "100% de bajar el At. Esp. de los rivales en 1.",
  "100% chance to lower the foe(s) Speed by 1.": "100% de bajar la Velocidad de los rivales en 1.",
  "100% chance to lower the target's Attack by 1.": "100% de bajar el Ataque del objetivo en 1.",
  "100% chance to lower the target's Defense by 1.": "100% de bajar la Defensa del objetivo en 1.",
  "100% chance to lower the target's Sp. Atk by 1.": "100% de bajar el At. Esp. del objetivo en 1.",
  "100% chance to lower the target's Sp. Def by 1.": "100% de bajar la Def. Esp. del objetivo en 1.",
  "100% chance to lower the target's Sp. Def by 2.": "100% de bajar la Def. Esp. del objetivo en 2.",
  "100% chance to lower the target's Speed by 1.": "100% de bajar la Velocidad del objetivo en 1.",
  "100% chance to lower the target's accuracy by 1.": "100% de bajar la Precisión del objetivo en 1.",
  "100% chance to paralyze the target.": "100% de prob. de paralizar al objetivo.",
  "100% chance to raise the user's Defense by 1.": "100% de subir la Defensa del usuario en 1.",
  "100% chance to raise the user's Sp. Atk by 1.": "100% de subir el At. Esp. del usuario en 1.",
  "100% chance to raise the user's Speed by 1.": "100% de subir la Velocidad del usuario en 1.",
  "100% confuse target that had a stat rise this turn.": "Confunde seguro al objetivo que haya subido una stat este turno.",
  "100% flinch. Fails unless target using priority.": "Hace retroceder seguro. Falla salvo que el objetivo use prioridad.",
  "20% burn. Recovers 50% dmg dealt. Thaws foe(s).": "20% de quemar. Recupera el 50% del daño. Descongela a los rivales.",
  "20% chance to confuse the target.": "20% de prob. de confundir al objetivo.",
  "20% chance to lower the target's Defense by 1.": "20% de prob. de bajar la Defensa del objetivo en 1.",
  "20% chance to lower the target's Sp. Def by 1.": "20% de prob. de bajar la Def. Esp. del objetivo en 1.",
  "20% chance to make the target flinch.": "20% de prob. de hacer retroceder al objetivo.",
  "20% chance to paralyze or burn or freeze target.": "20% de prob. de paralizar, quemar o congelar al objetivo.",
  "20% chance to raise the user's Attack by 1.": "20% de prob. de subir el Ataque del usuario en 1.",
  "20% psn. Physical+contact if it would be stronger.": "20% de envenenar. Físico y por contacto si así es más fuerte.",
  "2x power if target is grounded in Electric Terrain.": "Doble potencia si el objetivo está en tierra en Campo Eléctrico.",
  "2x power if the user had a stat lowered this turn.": "Doble potencia si al usuario le bajaron una stat este turno.",
  "30% burn. 2x power if target is already statused.": "30% de quemar. Doble potencia si el objetivo ya tiene estado.",
  "30% chance to burn adjacent Pokemon.": "30% de prob. de quemar a los Pokémon adyacentes.",
  "30% chance to burn the target. Thaws target.": "30% de prob. de quemar al objetivo. Lo descongela.",
  "30% chance to confuse target. Can't miss in rain.": "30% de prob. de confundir al objetivo. No falla con lluvia.",
  "30% chance to lower the foe(s) accuracy by 1.": "30% de prob. de bajar la Precisión de los rivales en 1.",
  "30% chance to lower the target's Defense by 1.": "30% de prob. de bajar la Defensa del objetivo en 1.",
  "30% chance to make the foe(s) flinch.": "30% de prob. de hacer retroceder a los rivales.",
  "30% chance to make the target flinch.": "30% de prob. de hacer retroceder al objetivo.",
  "30% chance to paralyze adjacent Pokemon.": "30% de prob. de paralizar a los Pokémon adyacentes.",
  "30% chance to paralyze the target.": "30% de prob. de paralizar al objetivo.",
  "30% chance to paralyze. Can't miss in rain.": "30% de prob. de paralizar. No falla con lluvia.",
  "30% chance to poison the target.": "30% de prob. de envenenar al objetivo.",
  "30% chance to sleep, poison, or paralyze target.": "30% de prob. de dormir, envenenar o paralizar al objetivo.",
  "30% confusion. User loses 50% max HP if miss.": "30% de confundir. Si falla, el usuario pierde el 50% de sus PS máx.",
  "40% chance to lower the target's accuracy by 1.": "40% de prob. de bajar la Precisión del objetivo en 1.",
  "5 turns. Can't status,-Dragon power vs grounded.": "5 turnos: nadie sufre estados; los Dragón pierden potencia contra rivales en tierra.",
  "5 turns. Grounded: +Electric power, can't sleep.": "5 turnos: en tierra, +potencia Eléctrico y no se puede dormir.",
  "5 turns. Grounded: +Grass power, +1/16 max HP.": "5 turnos: en tierra, +potencia Planta y +1/16 de PS máx.",
  "5 turns. Grounded: +Psychic power, priority-safe.": "5 turnos: en tierra, +potencia Psíquico e inmune a prioridad.",
  "5 turns: no Ground immunities, 1.67x accuracy.": "5 turnos: sin inmunidades a Tierra y precisión x1,67.",
  "50% chance to badly poison the target.": "50% de prob. de envenenar gravemente al objetivo.",
  "50% chance to lower the target's Defense by 1.": "50% de prob. de bajar la Defensa del objetivo en 1.",
  "50% chance to raise the user's Sp. Atk by 1.": "50% de prob. de subir el At. Esp. del usuario en 1.",
  "50% psn. 2x power if target already poisoned.": "50% de envenenar. Doble potencia si el objetivo ya está envenenado.",
  "70% chance to raise the user's Sp. Atk by 1.": "70% de prob. de subir el At. Esp. del usuario en 1.",
  "A target of the opposite gender gets infatuated.": "Enamora a un objetivo del sexo opuesto.",
  "Adds Ghost to the target's type(s).": "Añade el tipo Fantasma al objetivo.",
  "Adds Grass to the target's type(s).": "Añade el tipo Planta al objetivo.",
  "All active Pokemon consume held Berries.": "Todos los Pokémon en combate consumen su baya.",
  "All active Pokemon will faint in 3 turns.": "Todos los Pokémon en combate se debilitan en 3 turnos.",
  "All healthy allies aid in damaging the target.": "Todos los aliados sanos ayudan a dañar al objetivo.",
  "Ally: Crit ratio +1, or +2 if ally is Dragon type.": "Aliado: +1 de crítico (o +2 si es de tipo Dragón).",
  "Always results in a critical hit.": "Siempre asesta un golpe crítico.",
  "Always results in a critical hit; no accuracy check.": "Siempre asesta un golpe crítico; no comprueba precisión.",
  "Averages Attack and Sp. Atk stats with target.": "Promedia el Ataque y el At. Esp. con el objetivo.",
  "Averages Defense and Sp. Def stats with target.": "Promedia la Defensa y la Def. Esp. con el objetivo.",
  "Badly poisons the target. Poison types can't miss.": "Envenena gravemente al objetivo. Los Veneno no fallan.",
  "Bounces turn 1. Hits turn 2. 30% paralyze.": "Salta el turno 1 y golpea el 2. 30% de paralizar.",
  "Burns on contact with the user before it moves.": "Quema por contacto al rival antes de que actúe.",
  "Burns the target.": "Quema al objetivo.",
  "Cannot be selected the turn after it's used.": "No puede seleccionarse el turno siguiente a su uso.",
  "Causes the target to become confused.": "Confunde al objetivo.",
  "Causes the target to fall asleep.": "Duerme al objetivo.",
  "Changes the target's move to Electric this turn.": "Cambia el movimiento del objetivo a tipo Eléctrico este turno.",
  "Changes the target's type to Psychic.": "Cambia el tipo del objetivo a Psíquico.",
  "Changes the target's type to Water.": "Cambia el tipo del objetivo a Agua.",
  "Charges turn 1. Hits turn 2. No charge in sunlight.": "Carga el turno 1 y golpea el 2. No carga con sol.",
  "Charges, then hits turn 2. 30% flinch. High crit.": "Carga y golpea el turno 2. 30% de retroceso. Alto crítico.",
  "Combines Flying in its type effectiveness.": "Añade el tipo Volador al cálculo de eficacia.",
  "Confuses adjacent Pokemon.": "Confunde a los Pokémon adyacentes.",
  "Confuses the target.": "Confunde al objetivo.",
  "Copies target's stats, moves, types, and Ability.": "Copia stats, movimientos, tipos y habilidad del objetivo.",
  "Copies the target's current stat stages.": "Copia los cambios de stats actuales del objetivo.",
  "Cures the user's party of all status conditions.": "Cura todos los estados del equipo del usuario.",
  "Curses if Ghost, else -1 Spe, +1 Atk, +1 Def.": "Si es Fantasma, maldice; si no, -1 Vel., +1 Ataque, +1 Defensa.",
  "Damages target based on Defense, not Sp. Def.": "Daña al objetivo según su Defensa, no su Def. Esp.",
  "Deals 1/16 max HP each turn; 1/8 on Steel, Water.": "Daña 1/16 de PS máx. por turno; 1/8 a Acero y Agua.",
  "Destroys screens, unless the target is immune.": "Destruye las pantallas salvo que el objetivo sea inmune.",
  "Destroys screens. Type depends on user's form.": "Destruye las pantallas. El tipo depende de la forma del usuario.",
  "Digs underground turn 1, strikes turn 2.": "Cava el turno 1 y golpea el 2.",
  "Disappears turn 1. Hits turn 2. Breaks protection.": "Desaparece el turno 1 y golpea el 2. Rompe la protección.",
  "Dives underwater turn 1, strikes turn 2.": "Bucea el turno 1 y golpea el 2.",
  "Does damage equal to 1/2 target's current HP.": "Hace daño igual a la mitad de los PS actuales del objetivo.",
  "Does damage equal to the user's HP. User faints.": "Hace daño igual a los PS del usuario. El usuario se debilita.",
  "Does damage equal to the user's level.": "Hace daño igual al nivel del usuario.",
  "Eliminates all stat changes.": "Elimina todos los cambios de stats.",
  "Ends the effects of terrain.": "Termina los efectos del campo.",
  "Fails if the target has no held item.": "Falla si el objetivo no lleva objeto.",
  "Fails if the user takes damage before it hits.": "Falla si el usuario recibe daño antes de golpear.",
  "Fails if there is no terrain active. Ends the terrain.": "Falla si no hay campo activo. Termina el campo.",
  "Fails unless each known move has been used.": "Falla salvo que se hayan usado todos sus movimientos.",
  "Fails unless the user has a berry. User eats Berry, Def +2.": "Falla salvo que el usuario lleve baya. La come y +2 Defensa.",
  "Fails unless the user has eaten a Berry.": "Falla salvo que el usuario haya comido una baya.",
  "Flies up on first turn, then strikes the next turn.": "Vuela el primer turno y golpea el siguiente.",
  "Flings the user's item at the target. Power varies.": "Lanza el objeto del usuario al objetivo. La potencia varía.",
  "For 2 turns, the target cannot use sound moves.": "Durante 2 turnos, el objetivo no puede usar movimientos de sonido.",
  "For 2 turns, the target is prevented from healing.": "Durante 2 turnos, el objetivo no puede curarse.",
  "For 4 turns, allies' Speed is doubled.": "Durante 4 turnos, la Velocidad de los aliados se duplica.",
  "For 4 turns, disables the target's last move used.": "Durante 4 turnos, anula el último movimiento del objetivo.",
  "For 5 turns, a sandstorm rages. Rock: 1.5x SpD.": "Durante 5 turnos hay tormenta de arena. Roca: x1,5 Def. Esp.",
  "For 5 turns, all Defense and Sp. Def stats switch.": "Durante 5 turnos, se intercambian Defensa y Def. Esp.",
  "For 5 turns, all held items have no effect.": "Durante 5 turnos, los objetos no tienen efecto.",
  "For 5 turns, damage to allies halved. Snow only.": "Durante 5 turnos, el daño a los aliados se reduce a la mitad. Solo con nieve.",
  "For 5 turns, heavy rain powers Water moves.": "Durante 5 turnos, llueve intensamente y se potencian los movimientos Agua.",
  "For 5 turns, intense sunlight powers Fire moves.": "Durante 5 turnos, hay sol intenso y se potencian los movimientos Fuego.",
  "For 5 turns, physical damage to allies is halved.": "Durante 5 turnos, el daño físico a los aliados se reduce a la mitad.",
  "For 5 turns, protects user's party from status.": "Durante 5 turnos, protege al equipo del usuario de los estados.",
  "For 5 turns, snow falls. Ice: 1.5x Def.": "Durante 5 turnos nieva. Hielo: x1,5 Defensa.",
  "For 5 turns, special damage to allies is halved.": "Durante 5 turnos, el daño especial a los aliados se reduce a la mitad.",
  "For 5 turns, the user has immunity to Ground.": "Durante 5 turnos, el usuario es inmune a Tierra.",
  "Forces the target to move last this turn.": "Obliga al objetivo a actuar el último este turno.",
  "Forces the target to switch to a random ally.": "Obliga al objetivo a cambiarse por un aliado al azar.",
  "Free user from hazards/bind/Leech Seed; +1 Spe.": "Libera al usuario de trampas, presa y Drenadoras; +1 Vel.",
  "Goes last. For 5 turns, turn order is reversed.": "Actúa el último. Durante 5 turnos se invierte el orden.",
  "Has 1/2 recoil.": "Retroceso de 1/2 del daño causado.",
  "Has 1/4 recoil.": "Retroceso de 1/4 del daño causado.",
  "Has 33% recoil.": "Retroceso del 33% del daño causado.",
  "Has 33% recoil. 10% chance to burn. Thaws user.": "Retroceso del 33%. 10% de quemar. Descongela al usuario.",
  "Has 33% recoil. 10% chance to paralyze target.": "Retroceso del 33%. 10% de paralizar al objetivo.",
  "Has a 30% chance this move's power is doubled.": "30% de prob. de que su potencia se duplique.",
  "Heals 50% HP. Flying-type removed 'til turn ends.": "Cura el 50% de PS. Pierde el tipo Volador hasta el fin del turno.",
  "Heals the target by 50% of its max HP.": "Cura al objetivo el 50% de sus PS máx.",
  "Heals the user and its allies by 1/4 their max HP.": "Cura al usuario y a sus aliados 1/4 de sus PS máx.",
  "Heals the user based on uses of Stockpile.": "Cura al usuario según los usos de Reserva.",
  "Heals the user by 50% of its max HP.": "Cura al usuario el 50% de sus PS máx.",
  "Heals the user by a weather-dependent amount.": "Cura al usuario una cantidad según el clima.",
  "High crit. Target: 50% -1 Defense, 30% flinch.": "Alto crítico. Objetivo: 50% -1 Defensa, 30% retroceso.",
  "High critical hit ratio.": "Alta probabilidad de golpe crítico.",
  "High critical hit ratio. 10% chance to burn.": "Alta probabilidad de crítico. 10% de quemar.",
  "High critical hit ratio. 10% chance to poison.": "Alta probabilidad de crítico. 10% de envenenar.",
  "High critical hit ratio. Hits adjacent foes.": "Alta probabilidad de crítico. Golpea a los rivales adyacentes.",
  "Hits 10 times. Each hit can miss.": "Golpea 10 veces. Cada golpe puede fallar.",
  "Hits 2 times in one turn.": "Golpea 2 veces en un turno.",
  "Hits 2-5 times in one turn.": "Golpea de 2 a 5 veces en un turno.",
  "Hits 2-5 times. User: -1 Def, +1 Spe after last hit.": "Golpea de 2 a 5 veces. Tras el último: -1 Defensa, +1 Vel.",
  "Hits 3 times. Each hit can miss, but power rises.": "Golpea 3 veces. Cada golpe puede fallar, pero sube la potencia.",
  "Hits adjacent Pokemon. Double damage on Dig.": "Golpea a los Pokémon adyacentes. Doble daño durante Excavar.",
  "Hits adjacent Pokemon. Double damage on Dive.": "Golpea a los Pokémon adyacentes. Doble daño durante Buceo.",
  "Hits adjacent Pokemon. The user faints.": "Golpea a los Pokémon adyacentes. El usuario se debilita.",
  "Hits first. First turn out only. 100% flinch chance.": "Ataca primero. Solo el primer turno. 100% de hacer retroceder.",
  "Hits twice. Doubles: Tries to hit each foe once.": "Golpea dos veces. En dobles, intenta golpear a cada rival una vez.",
  "Hits two turns after being used.": "Golpea dos turnos después de usarse.",
  "Hurts foes on switch-in. Factors Rock weakness.": "Daña a los rivales al entrar, según su debilidad a Roca.",
  "Hurts grounded foes on switch-in. Max 3 layers.": "Daña a los rivales en tierra al entrar. Máx. 3 capas.",
  "If an opponent knocks out the user, it also faints.": "Si un rival debilita al usuario, también se debilita.",
  "If hit by an attack, returns 1.5x damage.": "Si lo golpea un ataque, devuelve x1,5 el daño.",
  "If hit by physical attack, returns double damage.": "Si lo golpea un ataque físico, devuelve el doble de daño.",
  "If hit by special attack, returns double damage.": "Si lo golpea un ataque especial, devuelve el doble de daño.",
  "If the target is an ally, heals 50% of its max HP.": "Si el objetivo es un aliado, le cura el 50% de sus PS máx.",
  "If the user has no item, it steals the target's.": "Si el usuario no lleva objeto, roba el del objetivo.",
  "Ignores the target's stat stage changes.": "Ignora los cambios de stats del objetivo.",
  "Inverts the target's stat stages.": "Invierte los cambios de stats del objetivo.",
  "Lasts 2-3 turns. Confuses the user afterwards.": "Dura 2-3 turnos. Después confunde al usuario.",
  "Lasts 3 turns. Active Pokemon cannot fall asleep.": "Dura 3 turnos. Los Pokémon en combate no pueden dormirse.",
  "Less power as user's HP decreases. Hits foe(s).": "Menos potencia cuanto menos PS le quedan al usuario. Golpea a los rivales.",
  "Lowers Def, SpD by 1; raises Atk, SpA, Spe by 2.": "Baja Defensa y Def. Esp. en 1; sube Ataque, At. Esp. y Vel. en 2.",
  "Lowers Speed of grounded foes by 1 on switch-in.": "Baja en 1 la Velocidad de los rivales en tierra al entrar.",
  "Lowers target's Atk, Sp. Atk by 1. User switches.": "Baja el Ataque y At. Esp. del objetivo en 1. El usuario se cambia.",
  "Lowers target's Attack, Sp. Atk by 2. User faints.": "Baja el Ataque y At. Esp. del objetivo en 2. El usuario se debilita.",
  "Lowers the PP of the target's last move by 4.": "Reduce en 4 los PP del último movimiento del objetivo.",
  "Lowers the foe(s) Speed by 2.": "Baja la Velocidad de los rivales en 2.",
  "Lowers the foe(s) evasiveness by 2.": "Baja la Evasión de los rivales en 2.",
  "Lowers the target's Attack and Defense by 1.": "Baja el Ataque y la Defensa del objetivo en 1.",
  "Lowers the target's Attack and Sp. Atk by 1.": "Baja el Ataque y el At. Esp. del objetivo en 1.",
  "Lowers the target's Attack by 1.": "Baja el Ataque del objetivo en 1.",
  "Lowers the target's Attack by 2.": "Baja el Ataque del objetivo en 2.",
  "Lowers the target's Defense by 2.": "Baja la Defensa del objetivo en 2.",
  "Lowers the target's HP to the user's HP.": "Iguala los PS del objetivo a los del usuario.",
  "Lowers the target's Sp. Atk by 2.": "Baja el At. Esp. del objetivo en 2.",
  "Lowers the target's Sp. Def by 2.": "Baja la Def. Esp. del objetivo en 2.",
  "Lowers the target's Speed by 2 and poisons it.": "Baja la Velocidad del objetivo en 2 y lo envenena.",
  "Lowers the target's Speed by 2.": "Baja la Velocidad del objetivo en 2.",
  "Lowers the user's Attack and Defense by 1.": "Baja el Ataque y la Defensa del usuario en 1.",
  "Lowers the user's Defense and Sp. Def by 1.": "Baja la Defensa y la Def. Esp. del usuario en 1.",
  "Lowers the user's Defense by 1.": "Baja la Defensa del usuario en 1.",
  "Lowers the user's Sp. Atk by 2.": "Baja el At. Esp. del usuario en 2.",
  "Lowers the user's Sp. Atk by 2. Hits foe(s).": "Baja el At. Esp. del usuario en 2. Golpea a los rivales.",
  "Lowers the user's Speed by 1.": "Baja la Velocidad del usuario en 1.",
  "More power the faster the user is than the target.": "Más potencia cuanto más rápido sea el usuario que el objetivo.",
  "More power the heavier the target.": "Más potencia cuanto más pese el objetivo.",
  "More power the heavier the user than the target.": "Más potencia cuanto más pese el usuario respecto al objetivo.",
  "More power the less HP the user has left.": "Más potencia cuanto menos PS le queden al usuario.",
  "More power the more HP the target has left.": "Más potencia cuantos más PS le queden al objetivo.",
  "More power the slower the user than the target.": "Más potencia cuanto más lento sea el usuario que el objetivo.",
  "More power with more uses of Stockpile.": "Más potencia cuantos más usos de Reserva.",
  "Morpeko: Electric; Hangry: Dark; 100% +1 Spe.": "Morpeko: Eléctrico; forma Voraz: Siniestro; 100% +1 Vel.",
  "Nearly always goes first.": "Casi siempre ataca primero.",
  "Nearly always goes first. First turn out only.": "Casi siempre ataca primero. Solo el primer turno.",
  "Next turn, 50% of the user's max HP is restored.": "Al turno siguiente, el usuario recupera el 50% de sus PS máx.",
  "No additional effect.": "Sin efecto adicional.",
  "No additional effect. Hits adjacent Pokemon.": "Sin efecto adicional. Golpea a los Pokémon adyacentes.",
  "No additional effect. Hits adjacent foes.": "Sin efecto adicional. Golpea a los rivales adyacentes.",
  "No foe can use any move known by the user.": "Ningún rival puede usar movimientos que conozca el usuario.",
  "Nullifies Detect, Protect, and Quick/Wide Guard.": "Anula Detección, Protección y Anticipo/Vasta Guardia.",
  "Nullifies the target's Ability.": "Anula la habilidad del objetivo.",
  "OHKOs non-Ice targets. Fails if user's lower level.": "Debilita de un golpe a objetivos no Hielo. Falla si el usuario es de menor nivel.",
  "OHKOs the target. Fails if user is a lower level.": "Debilita al objetivo de un golpe. Falla si el usuario es de menor nivel.",
  "One adjacent ally's move power is 1.5x this turn.": "La potencia del movimiento de un aliado adyacente es x1,5 este turno.",
  "Paralyzes the target.": "Paraliza al objetivo.",
  "Poisons foes, frees user from hazards/bind/leech.": "Envenena a los rivales y libera al usuario de trampas, presa y drenado.",
  "Poisons grounded foes on switch-in. Max 2 layers.": "Envenena a los rivales en tierra al entrar. Máx. 2 capas.",
  "Poisons the target.": "Envenena al objetivo.",
  "Power doubles and type varies in each weather.": "Dobla la potencia y su tipo varía según el clima.",
  "Power doubles if others used Round this turn.": "Dobla la potencia si otros han usado Canon este turno.",
  "Power doubles if target was damaged this turn.": "Dobla la potencia si el objetivo recibió daño este turno.",
  "Power doubles if the target has a status ailment.": "Dobla la potencia si el objetivo tiene un problema de estado.",
  "Power doubles if the target is poisoned.": "Dobla la potencia si el objetivo está envenenado.",
  "Power doubles if the user has no held item.": "Dobla la potencia si el usuario no lleva objeto.",
  "Power doubles if the user moves after the target.": "Dobla la potencia si el usuario actúa tras el objetivo.",
  "Power doubles if the user's last move failed.": "Dobla la potencia si el último movimiento del usuario falló.",
  "Power doubles if user is burn/poison/paralyzed.": "Dobla la potencia si el usuario está quemado, envenenado o paralizado.",
  "Power doubles if user is damaged by the target.": "Dobla la potencia si el objetivo daña al usuario.",
  "Prevents all Pokemon from switching next turn.": "Impide que ningún Pokémon se cambie el turno siguiente.",
  "Prevents moves from affecting the user this turn.": "Evita que los movimientos afecten al usuario este turno.",
  "Prevents the target from switching out.": "Impide que el objetivo se cambie.",
  "Protects allies from multi-target moves this turn.": "Protege a los aliados de movimientos multiobjetivo este turno.",
  "Protects allies from priority attacks this turn.": "Protege a los aliados de ataques con prioridad este turno.",
  "Protects from damaging attacks. Contact: -1 Atk.": "Protege de ataques con daño. Por contacto: -1 Ataque.",
  "Protects from moves. Contact: loses 1/8 max HP.": "Protege de los movimientos. Por contacto: pierde 1/8 de PS máx.",
  "Protects from moves. Contact: poison.": "Protege de los movimientos. Por contacto: envenena.",
  "Puts the target to sleep after 1 turn.": "Duerme al objetivo tras 1 turno.",
  "Raises Def, Sp. Def of allies with Plus/Minus by 1.": "Sube en 1 la Defensa y Def. Esp. de los aliados con Más/Menos.",
  "Raises Sp. Atk by 1, hits turn 2. Rain: no charge.": "Sube +1 At. Esp. y golpea el turno 2. Con lluvia no carga.",
  "Raises a random stat of the user or an ally by 2.": "Sube en 2 una stat al azar del usuario o de un aliado.",
  "Raises all stats by 1 (not acc/eva). Traps user.": "Sube todas las stats en 1 (no prec/eva). Atrapa al usuario.",
  "Raises an ally's Attack and Defense by 1.": "Sube en 1 el Ataque y la Defensa de un aliado.",
  "Raises an ally's Sp. Def by 1.": "Sube en 1 la Def. Esp. de un aliado.",
  "Raises target's Atk by 2 and lowers its Def by 2.": "Sube en 2 el Ataque del objetivo y baja en 2 su Defensa.",
  "Raises the target's Attack and Sp. Atk by 2.": "Sube en 2 el Ataque y el At. Esp. del objetivo.",
  "Raises the target's Attack by 2 and confuses it.": "Sube en 2 el Ataque del objetivo y lo confunde.",
  "Raises the target's Sp. Atk by 1 and confuses it.": "Sube en 1 el At. Esp. del objetivo y lo confunde.",
  "Raises the user's Attack and Defense by 1.": "Sube en 1 el Ataque y la Defensa del usuario.",
  "Raises the user's Attack and Speed by 1.": "Sube en 1 el Ataque y la Velocidad del usuario.",
  "Raises the user's Attack by 2.": "Sube en 2 el Ataque del usuario.",
  "Raises the user's Defense and Sp. Def by 1.": "Sube en 1 la Defensa y la Def. Esp. del usuario.",
  "Raises the user's Defense by 2.": "Sube en 2 la Defensa del usuario.",
  "Raises the user's Defense by 3.": "Sube en 3 la Defensa del usuario.",
  "Raises the user's Sp. Atk and Sp. Def by 1.": "Sube en 1 el At. Esp. y la Def. Esp. del usuario.",
  "Raises the user's Sp. Atk by 2.": "Sube en 2 el At. Esp. del usuario.",
  "Raises the user's Sp. Atk, Sp. Def, Speed by 1.": "Sube en 1 el At. Esp., la Def. Esp. y la Velocidad del usuario.",
  "Raises the user's Sp. Def by 2.": "Sube en 2 la Def. Esp. del usuario.",
  "Raises the user's Speed by 2.": "Sube en 2 la Velocidad del usuario.",
  "Raises the user's and ally's Attack by 1.": "Sube en 1 el Ataque del usuario y de su aliado.",
  "Raises the user's critical hit ratio by 2.": "Sube en 2 la probabilidad de crítico del usuario.",
  "Raises the user's evasiveness by 1.": "Sube en 1 la Evasión del usuario.",
  "Raises the user's evasiveness by 2.": "Sube en 2 la Evasión del usuario.",
  "Raises user's Attack and Sp. Atk by 1; 2 in Sun.": "Sube en 1 el Ataque y At. Esp. del usuario; en 2 con sol.",
  "Raises user's Attack by 3 if this KOes the target.": "Sube en 3 el Ataque del usuario si debilita al objetivo.",
  "Raises user's Attack, Defense, accuracy by 1.": "Sube en 1 el Ataque, la Defensa y la Precisión del usuario.",
  "Raises user's Defense, Sp. Def by 1. Max 3 uses.": "Sube en 1 la Defensa y Def. Esp. del usuario. Máx. 3 usos.",
  "Raises user's Sp. Atk by 1 on turn 1. Hits turn 2.": "Sube en 1 el At. Esp. el turno 1 y golpea el 2.",
  "Removes 3 PP from the target's last move.": "Quita 3 PP al último movimiento del objetivo.",
  "Removes adjacent Pokemon's held items.": "Quita el objeto a los Pokémon adyacentes.",
  "Removes the target's Ground immunity.": "Elimina la inmunidad a Tierra del objetivo.",
  "Resets all of the target's stat stages to 0.": "Restablece a 0 todos los cambios de stats del objetivo.",
  "Restores the item the user last used.": "Recupera el último objeto usado por el usuario.",
  "Sets Stealth Rock on the target's side.": "Coloca Trampa Rocas en el lado del objetivo.",
  "Sets a layer of Spikes on the opposing side.": "Coloca una capa de Púas en el lado rival.",
  "Shares HP of user and target equally.": "Reparte por igual los PS del usuario y del objetivo.",
  "Starts Snow. User switches out.": "Invoca nieve. El usuario se cambia.",
  "Super effective on Water.": "Supereficaz contra Agua.",
  "Swaps Attack and Sp. Atk stat stages with target.": "Intercambia los cambios de Ataque y At. Esp. con el objetivo.",
  "Swaps Defense and Sp. Def changes with target.": "Intercambia los cambios de Defensa y Def. Esp. con el objetivo.",
  "Swaps Speed stat with target.": "Intercambia la Velocidad con el objetivo.",
  "Switches user's Attack and Defense stats.": "Intercambia el Ataque y la Defensa del usuario.",
  "Target can't select the same move twice in a row.": "El objetivo no puede usar el mismo movimiento dos veces seguidas.",
  "Target can't use status moves its next 3 turns.": "El objetivo no puede usar movimientos de estado durante 3 turnos.",
  "Target repeats its last move for its next 3 turns.": "El objetivo repite su último movimiento durante 3 turnos.",
  "Target's Speed is lowered by 1 stage for 3 turns.": "La Velocidad del objetivo baja 1 nivel durante 3 turnos.",
  "Target: 100% -1 Def. During Gravity: 1.5x power.": "Objetivo: 100% -1 Defensa. Con Gravedad: x1,5 potencia.",
  "The foes' moves target the user on the turn used.": "Los movimientos de los rivales apuntan al usuario ese turno.",
  "The target immediately uses its last used move.": "El objetivo usa de inmediato su último movimiento.",
  "The target is cured of its burn.": "Cura la quemadura del objetivo.",
  "The target makes its move right after the user.": "El objetivo actúa justo después del usuario.",
  "The target's Ability becomes Insomnia.": "La habilidad del objetivo pasa a ser Insomnio.",
  "The target's Ability becomes Simple.": "La habilidad del objetivo pasa a ser Simple.",
  "The target's Ability changes to match the user's.": "La habilidad del objetivo pasa a ser la del usuario.",
  "The user and the target trade Abilities.": "El usuario y el objetivo intercambian habilidades.",
  "This move does not check accuracy.": "Este movimiento no comprueba la precisión.",
  "Traps and damages the target for 4-5 turns.": "Atrapa y daña al objetivo durante 4-5 turnos.",
  "Traps/grounds user; heals 1/16 max HP per turn.": "Atrapa al usuario en tierra; cura 1/16 de PS máx. por turno.",
  "User +1 Atk, Spe. Clears all substitutes/hazards.": "Usuario +1 Ataque y Vel. Elimina sustitutos y trampas.",
  "User and ally swap positions; using again can fail.": "El usuario y un aliado intercambian posición; reutilizar puede fallar.",
  "User becomes the same type as the target.": "El usuario adopta el tipo del objetivo.",
  "User cannot move next turn.": "El usuario no puede actuar el turno siguiente.",
  "User faints. Next hurt Pokemon is fully healed.": "El usuario se debilita. El siguiente Pokémon herido se cura del todo.",
  "User faints. User on Misty Terrain: 1.5x power.": "El usuario se debilita. En Campo de Niebla: x1,5 potencia.",
  "User heals HP=target's Atk stat. Lowers Atk by 1.": "El usuario cura PS igual al Ataque del objetivo y se lo baja en 1.",
  "User is hurt by 50% of its max HP if it misses.": "Si falla, el usuario pierde el 50% de sus PS máx.",
  "User loses 33% of its max HP. +1 to all stats.": "El usuario pierde el 33% de sus PS máx. +1 a todas las stats.",
  "User loses 50% max HP.": "El usuario pierde el 50% de sus PS máx.",
  "User loses 50% max HP. Maximizes Attack.": "El usuario pierde el 50% de sus PS máx. Maximiza el Ataque.",
  "User must be asleep. 30% chance to flinch target.": "El usuario debe estar dormido. 30% de hacer retroceder al objetivo.",
  "User must be asleep. Uses another known move.": "El usuario debe estar dormido. Usa otro de sus movimientos.",
  "User on Grassy Terrain: +1 priority.": "En Campo de Hierba: +1 de prioridad.",
  "User on Psychic Terrain: 1.5x power, hits foes.": "En Campo Psíquico: x1,5 potencia y golpea a los rivales.",
  "User on terrain: power doubles, type varies.": "Sobre un campo: dobla la potencia y su tipo varía.",
  "User recovers 1/16 max HP per turn.": "El usuario recupera 1/16 de PS máx. por turno.",
  "User recovers 50% of the damage dealt.": "El usuario recupera el 50% del daño causado.",
  "User recovers 75% of the damage dealt.": "El usuario recupera el 75% del daño causado.",
  "User replaces its Ability with the target's.": "El usuario adopta la habilidad del objetivo.",
  "User sleeps 2 turns and restores HP and status.": "El usuario duerme 2 turnos y recupera PS y estado.",
  "User steals and eats the target's Berry.": "El usuario roba y come la baya del objetivo.",
  "User survives attacks this turn with at least 1 HP.": "El usuario sobrevive a los ataques de este turno con al menos 1 PS.",
  "User switches its held item with the target's.": "El usuario intercambia su objeto con el del objetivo.",
  "User switches out after damaging the target.": "El usuario se cambia tras dañar al objetivo.",
  "User switches, passing stat changes and more.": "El usuario se cambia y pasa sus cambios de stats y más.",
  "User takes 1/2 its max HP to pass a substitute.": "El usuario usa 1/2 de sus PS máx. para pasar un sustituto.",
  "User takes 1/4 its max HP to put in a substitute.": "El usuario usa 1/4 de sus PS máx. para crear un sustituto.",
  "User's Fire type becomes typeless; must be Fire.": "El usuario Fuego pierde su tipo; debe ser de tipo Fuego.",
  "User's next move will not miss the target.": "El próximo movimiento del usuario no fallará al objetivo.",
  "Uses target's Attack stat in damage calculation.": "Usa el Ataque del objetivo en el cálculo de daño.",
  "Uses the last move used in the battle.": "Usa el último movimiento empleado en el combate.",
  "Uses user's Def stat as Atk in damage calculation.": "Usa la Defensa del usuario como Ataque en el cálculo de daño.",
  "Usually goes first.": "Suele atacar primero.",
  "Usually goes first. Fails if target is not attacking.": "Suele atacar primero. Falla si el objetivo no ataca.",
  "Usually goes first. Hits 2-5 times in one turn.": "Suele atacar primero. Golpea de 2 a 5 veces en un turno.",
};

// Traductor por reglas de respaldo (para descripciones no listadas arriba).
const STAT = {
  Attack: ['el', 'Ataque'], Defense: ['la', 'Defensa'],
  'Sp. Atk': ['el', 'At. Esp.'], 'Sp. Def': ['la', 'Def. Esp.'],
  Speed: ['la', 'Velocidad'], accuracy: ['la', 'precisión'], evasion: ['la', 'evasión'],
};
const STATRE = 'Attack|Defense|Sp\\. Atk|Sp\\. Def|Speed|accuracy|evasion';
const EFF = { burn: 'quemar', freeze: 'congelar', paralyze: 'paralizar', poison: 'envenenar', confuse: 'confundir' };

function ruleTranslate(en) {
  let r = en;
  const who = (w) => w.includes('target') ? 'del objetivo' : w.includes('foe') ? 'de los rivales' : 'del usuario';
  r = r.replace(new RegExp(`(lower|raise) (?:the )?(target's|foe\\(s\\)'?|user's) (${STATRE}) by (\\d)`, 'g'),
    (m, dir, w, st, n) => { const [art, name] = STAT[st]; return `${dir === 'lower' ? 'bajar' : 'subir'} ${art} ${name} ${who(w)} en ${n}`; });
  r = r.replace(/make (?:the )?target flinch/g, 'hacer retroceder al objetivo');
  r = r.replace(/make (?:the )?foe\(s\) flinch/g, 'hacer retroceder a los rivales');
  for (const [k, es] of Object.entries(EFF)) {
    r = r.replace(new RegExp(`${k} (?:the )?target`, 'g'), `${es} al objetivo`);
    r = r.replace(new RegExp(`${k} (?:the )?foe\\(s\\)`, 'g'), `${es} a los rivales`);
  }
  r = r.replace(/(\d+)% chance to /g, '$1% de prob. de ');
  for (const [k, es] of Object.entries(EFF)) r = r.replace(new RegExp(`\\b${k}\\b`, 'g'), es);
  r = r.replace(/\bflinch\b/g, 'retroceso');
  return r;
}

export function translateDesc(en) {
  if (!en) return en;
  return WHOLE[en] ?? ruleTranslate(en);
}
